### ISSUE TITLE
Is this actively used?

### ISSUE THREAD

**Issue by janpio** [konotor/phonegap-sdk#4]
Hey, just looking at livechat/support solutions for our Cordova/Ionic app. Is this plugin actively used by anyone? Seems a bit quiet in here...

**Comment by janpio** [comment]
Ok, no response, seems to be dead. Shame.

**Comment by srikrishnan-ganesan** [comment]
Hi Jan,

This is actively used.

## 

Srikrishnan Ganesan
Co-Founder, Konotor.com
How do you talk to your mobile app users today? Check out Konotor!

http://twitter.com/srikrishnang
skype: srikrishnan.ganesan
phone: +91 9790987495 (India)

**Comment by srikrishnan-ganesan** [comment]
hi @piotrowski. This is actively used. Lets speak?

**Comment by srikrishnan-ganesan** [comment]
I can update the files to reflect our latest SDK and guide you through this. Was about to shoot out a mail to you btw.

**Comment by janpio** [comment]
Thanks, for now we are just looking at different solutions that offer updated Cordova plugins to implement. You are now back on that list :)
